services:
  database:
    image: postgres:16.11-alpine
    container_name: database
    restart: always
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      - yetanotherecommerce_net
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: yetanotherecommerce
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s

  servicebus-emulator:
    image: mcr.microsoft.com/azure-messaging/servicebus-emulator:latest
    container_name: servicebus-emulator
    ports:
      - 5672:5672
    volumes:
      - ${CONFIG_PATH}:/ServiceBus_Emulator/ConfigFiles/Config.json
    environment:
      SQL_SERVER: mssql
      MSSQL_SA_PASSWORD: ${MSSQL_SA_PASSWORD}
      ACCEPT_EULA: ${ACCEPT_EULA}
    depends_on:
      - mssql
    networks:
      sb-emulator:
        aliases:
          - sb-emulator

  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: mssql
    environment:
      ACCEPT_EULA: ${ACCEPT_EULA}
      MSSQL_SA_PASSWORD: ${MSSQL_SA_PASSWORD}
    networks:
      sb-emulator:
        aliases:
          - mssql
  
  backend:
    build:
      context: ./apps/backend
      dockerfile: Dockerfile.Dev
    container_name: backend-dev
    ports:
      - 5001:5001
    networks:
      - yetanotherecommerce_net
    depends_on:
      database:
        condition: service_healthy

  frontend:
    build:
      context: ./apps/frontend
      dockerfile: Dockerfile.Dev
    container_name: frontend-dev
    ports:
      - 5173:5173
    volumes:
      - type: bind
        source: ./apps/frontend
        target: /usr/src/app
      - type: volume
        target: /usr/src/app/node_modules
    environment:
      VITE_API_BASE_URL: "http://localhost:5001"
    networks:
      - yetanotherecommerce_net

volumes:
  pgdata:

networks:
  yetanotherecommerce_net:
    driver: bridge
  sb-emulator:
